### ISSUE TITLE
Due date not showing properly

### ISSUE THREAD

**Issue by arpit-saxena** [enigmaiitd/CampusHack#12]
![screenshot_1549804863](https://user-images.githubusercontent.com/14573995/52534228-ff9d7700-2d64-11e9-8210-d43ad7def8d0.png)

**Comment by tmibvishal** [comment]
oh ya there is no month in the due date

**Comment by tmibvishal** [comment]
Fixed in this commit
https://github.com/enigmaiitd/CampusHack/commit/6e2fb96f49fdfe571a01ac5b7830d2437ef8b7e7
